"""add call listen session

Revision ID: 7fa8c3081305
Revises: 5fe973fcb8fd
Create Date: 2026-03-20 12:54:43.974312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fa8c3081305'
down_revision: Union[str, Sequence[str], None] = '5fe973fcb8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. создаем roles
    op.create_table(
        'roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )

    # 2. создаем role_permissions
    op.create_table(
        'role_permissions',
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id']),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id']),
        sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )

    # 3. добавляем колонку (nullable=True!!!)
    op.add_column('users', sa.Column('role_id', sa.UUID(), nullable=True))

    # 4. создаем роли
    op.execute("""
        INSERT INTO roles (id, code)
        VALUES
            (gen_random_uuid(), 'ADMIN'),
            (gen_random_uuid(), 'USER')
    """)

    # 5. переносим данные из старого role → role_id
    op.execute("""
               UPDATE users u
               SET role_id = r.id FROM roles r
               WHERE r.code = u.role::text
               """)

    # 6. fallback (если вдруг были NULL)
    op.execute("""
        UPDATE users
        SET role_id = (SELECT id FROM roles WHERE code = 'USER' LIMIT 1)
        WHERE role_id IS NULL
    """)

    # 7. делаем NOT NULL
    op.alter_column('users', 'role_id', nullable=False)

    # 8. FK
    op.create_foreign_key(
        'fk_users_role',
        'users',
        'roles',
        ['role_id'],
        ['id']
    )

    # 9. удаляем старое поле
    op.drop_column('users', 'role')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='userrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    # ### end Alembic commands ###
